<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ashish-PC" name="com.qtpselenium.framework.suiteA.TestA1" tests="4" failures="0" timestamp="4 Mar 2015 03:09:56 GMT" time="76.288" errors="1">
  <testcase name="testA1" time="26.102" classname="com.qtpselenium.framework.suiteA.TestA1"/>
  <testcase name="testA1" time="17.083" classname="com.qtpselenium.framework.suiteA.TestA1">
    <error type="java.lang.AssertionError" message="FAIL - Not able to Login with Deault Username/password ">
      <![CDATA[java.lang.AssertionError: FAIL - Not able to Login with Deault Username/password 
	at org.testng.Assert.fail(Assert.java:94)
	at com.qtpselenium.framework.util.Keywords.reportFailureAndStop(Keywords.java:277)
	at com.qtpselenium.framework.util.Keywords.loginIfNotLoggedIn(Keywords.java:237)
	at com.qtpselenium.framework.util.Keywords.executeKeywords(Keywords.java:82)
	at com.qtpselenium.framework.suiteA.TestA1.testA1(TestA1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testA1 -->
  <testcase name="testA1" time="32.874" classname="com.qtpselenium.framework.suiteA.TestA1"/>
  <testcase name="testA1" time="0.229" classname="com.qtpselenium.framework.suiteA.TestA1"/>
</testsuite> <!-- com.qtpselenium.framework.suiteA.TestA1 -->
